=== Ortolang/diffusion/comp/src/main/resources/schema/olac.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net",
  "type": "object",
    "additionalProperties": false,
  "properties": {
    "identifier": {
      "id": "http://www.ortolang.fr/schema/olac#identifier",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#identifier/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#identifier/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#identifier/item/value",
              "type": "string"
          }
        }
      }
    },
    "title": {
      "id": "http://www.ortolang.fr/schema/olac#title",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#title/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#title/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#title/item/value",
              "type": "string"
          }
        }
      }
    },
    "creator": {
      "id": "http://www.ortolang.fr/schema/olac#creator",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#creator/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#creator/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#creator/item/value",
              "type": "string"
          }
        }
      }
    },
    "subject": {
      "id": "http://www.ortolang.fr/schema/olac#subject",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#subject/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#subject/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#subject/item/value",
              "type": "string"
          }
        }
      }
    },
    "description": {
      "id": "http://www.ortolang.fr/schema/olac#description",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#description/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#description/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#description/item/value",
              "type": "string"
          }
        }
      }
    },
    "publisher": {
      "id": "http://www.ortolang.fr/schema/olac#publisher",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#publisher/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#publisher/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#publisher/item/value",
              "type": "string"
          }
        }
      }
    },
    "contributor": {
      "id": "http://www.ortolang.fr/schema/olac#contributor",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#contributor/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#contributor/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#contributor/item/value",
              "type": "string"
          }
        }
      }
    },
    "date": {
      "id": "http://www.ortolang.fr/schema/olac#date",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#date/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#date/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#date/item/value",
              "type": "string"
          }
        }
      }
    },
    "type": {
      "id": "http://www.ortolang.fr/schema/olac#type",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#type/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#type/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#type/item/value",
              "type": "string"
          }
        }
      }
    },
    "format": {
      "id": "http://www.ortolang.fr/schema/olac#format",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#format/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#format/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#format/item/value",
              "type": "string"
          }
        }
      }
    },
    "source": {
      "id": "http://www.ortolang.fr/schema/olac#source",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#source/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#source/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#source/item/value",
              "type": "string"
          }
        }
      }
    },
    "language": {
      "id": "http://www.ortolang.fr/schema/olac#language",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#language/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#language/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#language/item/value",
              "type": "string"
          }
        }
      }
    },
    "relation": {
      "id": "http://www.ortolang.fr/schema/olac#relation",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#relation/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#relation/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#relation/item/value",
              "type": "string"
          }
        }
      }
    },
    "coverage": {
      "id": "http://www.ortolang.fr/schema/olac#coverage",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#coverage/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#coverage/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#coverage/item/value",
              "type": "string"
          }
        }
      }
    },
    "rights": {
      "id": "http://www.ortolang.fr/schema/olac#rights",
      "type": "array",
      "items": {
        "id": "http://www.ortolang.fr/schema/olac#rights/item",
        "type": "object",
        "properties": {
          "lang": {
              "id": "http://www.ortolang.fr/schema/olac#rights/item/lang",
              "type": "string"
          },
          "value": {
              "id": "http://www.ortolang.fr/schema/olac#rights/item/value",
              "type": "string"
          }
        }
      }
    }
  }
}

=== Ortolang/diffusion/comp/src/test/resources/json/sample-dc.json
{
	"title": [{
		"lang": "fr",
		"value": "Premier dossier"
	}],
	"description": [{
		"value": "Ce premier dossier permet de tester les métadonnées Dublin Core"
	},
	{
		"lang": "fr",
		"value": "Résumé des épisodes à venir"
	}],
	"coverage": [{
		"value": "Earth"
	}],
	"subject": [{
		"code": "narrative"
	}],
	"identifier": [{
		"value": "http://www.michel.com"
	}]
}
